Pandas IO
==========
This folder contains 4 datasets in different ascii-based files:
1. all values of the S&P500 index since its beginning until July 2014,
2. some stock values for 5 major stocks between 2005 and 2009,
3. some recent tick data (one value per minute) for the AAPL stock, and
4. all historical data for the NASDAQ stock exchange since its beginning downloaded from the web.

The goal of this exercise is to load each of these files into a `DataFrame` using `read_table` (and `read_html` for the bonus question), while doing some clean up. These four `DataFrame`s will represent the basis for upcoming financial tasks.

In [3]:
import pandas as pd

In [4]:
pd.read_csv('HistoricalS_and_P500.csv')

          Date     Open     High      Low    Close      Volume  Adj Close
0       7/8/14  1976.39  1976.39  1959.46  1963.71  3302430000    1963.71
1       7/7/14  1984.22  1984.22  1974.88  1977.65  2681260000    1977.65
2       7/3/14  1975.88  1985.59  1975.88  1985.44  1998090000    1985.44
3       7/2/14  1973.06  1976.67  1972.58  1974.62  2851480000    1974.62
4       7/1/14  1962.29  1978.58  1962.29  1973.32  3188240000    1973.32
5      6/30/14  1960.79  1964.24  1958.22  1960.23  3037350000    1960.23
6      6/27/14  1956.56  1961.47  1952.18  1960.96  4290590000    1960.96
7      6/26/14  1959.89  1959.89  1944.69  1957.22  2778840000    1957.22
8      6/25/14  1949.27  1960.83  1947.49  1959.53  3106710000    1959.53
9      6/24/14  1961.97  1968.17  1948.34  1949.98  3089700000    1949.98
10     6/23/14  1962.92  1963.74  1958.89  1962.61  2717630000    1962.61
11     6/20/14  1960.45  1963.91  1959.17  1962.87  4336240000    1962.87
12     6/19/14  1957.50  1959.87  1952.26  1959.48  2952150000    1959.48
13     6/18/14  1942.73  1957.74  1939.29  1956.98  3065220000    1956.98
14     6/17/14  1937.15  1943.69  1933.55  1941.99  2971260000    1941.99
15     6/16/14  1934.84  1941.15  1930.91  1937.78  2926130000    1937.78
16     6/13/14  1930.80  1937.30  1927.69  1936.16  2598230000    1936.16
17     6/12/14  1943.35  1943.35  1925.78  1930.11  3040480000    1930.11
18     6/11/14  1949.37  1949.37  1940.08  1943.89  2710620000    1943.89
19     6/10/14  1950.34  1950.86  1944.64  1950.79  2702360000    1950.79
20      6/9/14  1948.97  1955.55  1947.16  1951.27  2812180000    1951.27
21      6/6/14  1942.41  1949.44  1942.41  1949.44  2864300000    1949.44
22      6/5/14  1928.52  1941.74  1922.93  1940.46  3113270000    1940.46
23      6/4/14  1923.06  1928.63  1918.60  1927.88  2793920000    1927.88
24      6/3/14  1923.07  1925.07  1918.79  1924.24  2867180000    1924.24
25      6/2/14  1923.87  1925.88  1915.98  1924.97  2509020000    1924.97
26     5/30/14  1920.33  1924.03  1916.64  1923.57  3263490000    1923.57
27     5/29/14  1910.60  1920.03  1909.82  1920.03  2709050000    1920.03
28     5/28/14  1911.77  1914.46  1907.30  1909.78  2976450000    1909.78
29     5/27/14  1902.01  1912.28  1902.01  1911.91  2911020000    1911.91
...        ...      ...      ...      ...      ...         ...        ...
16202  2/14/50    17.06    17.06    17.06    17.06     2210000      17.06
16203  2/10/50    17.24    17.24    17.24    17.24     1790000      17.24
16204   2/9/50    17.28    17.28    17.28    17.28     1810000      17.28
16205   2/8/50    17.21    17.21    17.21    17.21     1470000      17.21
16206   2/7/50    17.23    17.23    17.23    17.23     1360000      17.23
16207   2/6/50    17.32    17.32    17.32    17.32     1490000      17.32
16208   2/3/50    17.29    17.29    17.29    17.29     2210000      17.29
16209   2/2/50    17.23    17.23    17.23    17.23     2040000      17.23
16210   2/1/50    17.05    17.05    17.05    17.05     1810000      17.05
16211  1/31/50    17.05    17.05    17.05    17.05     1690000      17.05
16212  1/30/50    17.02    17.02    17.02    17.02     1640000      17.02
16213  1/27/50    16.82    16.82    16.82    16.82     1250000      16.82
16214  1/26/50    16.73    16.73    16.73    16.73     1150000      16.73
16215  1/25/50    16.74    16.74    16.74    16.74     1700000      16.74
16216  1/24/50    16.86    16.86    16.86    16.86     1250000      16.86
16217  1/23/50    16.92    16.92    16.92    16.92     1340000      16.92
16218  1/20/50    16.90    16.90    16.90    16.90     1440000      16.90
16219  1/19/50    16.87    16.87    16.87    16.87     1170000      16.87
16220  1/18/50    16.85    16.85    16.85    16.85     1570000      16.85
16221  1/17/50    16.86    16.86    16.86    16.86     1790000      16.86
16222  1/16/50    16.72    16.72    16.72    16.72     1460000      16.72
16223  1/13/50    16.67    16.67    16.67    16.67     3330000      16.67
16224  1/12/50    16.76    16.76    16.76    16.76     2970000      16.76
16225  1/11/50    17.09    17.09    17.09    17.09     2630000      17.09
16226  1/10/50    17.03    17.03    17.03    17.03     2160000      17.03
16227   1/9/50    17.08    17.08    17.08    17.08     2520000      17.08
16228   1/6/50    16.98    16.98    16.98    16.98     2010000      16.98
16229   1/5/50    16.93    16.93    16.93    16.93     2550000      16.93
16230   1/4/50    16.85    16.85    16.85    16.85     1890000      16.85
16231   1/3/50    16.66    16.66    16.66    16.66     1260000      16.66

[16232 rows x 7 columns]

Question 1. 
-----------
The file ("adj_close_stock_data_yahoo_2005_2010.txt") is space delimited. More precisely, the separation can be any number of space characters. This file contains 8 columns. The first 3 are the year, month, and day of the trading day and the next 5 are the open prices for the 5 stocks: AAPL, GOOG, MSFT, PG, XOM. Additionally, the file contains some missing values in 2005. They are encoded as a `-` when corrupted data was collected for that day. Load the dataset into a `DataFrame` with a basic numbered index for now, making sure to encode the `-` symbols as `NaN` (missing values).

Note: the separator argument of `read_table` can receive a [regular expression](http://en.wikipedia.org/wiki/Regular_expression). `\\s` is any space character. `\\s+` is one or more space character.

In [5]:
pd.read_table("adj_close_stock_data_yahoo_2005_2010.txt",delim_whitespace=True)

      year  month  day   AAPL   GOOGL   MSFT     PG    XOM
0     2005      1    3   4.32  101.46  21.88      -  40.44
1     2005      1    4   4.37   97.35  21.96  41.79  40.16
2     2005      1    5    4.4   96.85  21.91  42.23  39.95
3     2005      1    6   4.41   94.37  21.89  42.43  40.46
4     2005      1    7   4.73   97.02  21.82  42.88   40.2
5     2005      1   10   4.71   97.63  21.93  43.22  40.35
6     2005      1   11   4.41   96.87  21.87  43.17  40.25
7     2005      1   12   4.47   97.79  21.91  43.33  40.84
8     2005      1   13   4.77   97.76   21.5  42.58  40.81
9     2005      1   14   4.79  100.09  21.37  42.85  41.23
10    2005      1   18   4.82  102.05  21.54  42.93  41.58
11    2005      1   19   4.77   98.75  21.26  43.66  41.21
12    2005      1   20   4.81   97.06  21.16  43.67  40.95
13    2005      1   21   4.81   94.23  20.99  42.86  40.72
14    2005      1   24   4.83   90.45  21.01  42.52  41.28
15    2005      1   25   4.92   88.65  21.29  42.92  41.44
16    2005      1   26   4.93   94.71  21.28   42.7  41.74
17    2005      1   27   4.96   94.13  21.37  42.61  41.78
18    2005      1   28   5.05   95.27  21.42  41.71  41.39
19    2005      1   31   5.25   97.91  21.51   41.0  41.66
20    2005      2    1   5.29   96.05   21.6  40.72  43.01
21    2005      2    2   5.44  103.08  21.65  41.13  43.54
22    2005      2    3      -  105.54  21.42  41.01  44.02
23    2005      2    4   5.38  102.28  21.54  40.53  44.64
24    2005      2    7   5.39   98.11  21.41  40.46  44.73
25    2005      2    8   5.52   99.42  21.47  40.04  45.25
26    2005      2    9   5.38   95.89  21.33  39.67  45.06
27    2005      2   10   5.35   94.08  21.33  39.76  45.71
28    2005      2   11   5.54   93.79  21.25  40.17  45.52
29    2005      2   14   5.78   96.59  21.28  40.59  46.11
...    ...    ...  ...    ...     ...    ...    ...    ...
1229  2009     11   18  28.12  288.61  26.73  53.74  67.03
1230  2009     11   19  27.38  286.78  26.44  53.52  66.48
1231  2009     11   20   27.3  285.27   26.3  53.22  66.24
1232  2009     11   23  28.11  291.47  26.58  54.02  67.41
1233  2009     11   24  27.92  291.84  26.55  54.08  67.66
1234  2009     11   25  27.88  293.16  26.45  54.14   68.1
1235  2009     11   27  27.39  290.17  25.94   53.8  66.68
1236  2009     11   30   27.3  291.79  26.11  53.69  66.85
1237  2009     12    1   26.9  295.23  26.64  54.17  67.72
1238  2009     12    2  26.79  294.05  26.44  54.42   67.5
1239  2009     12    3  26.83  293.16  26.48  53.87  66.78
1240  2009     12    4   26.4   292.8  26.62  53.91  66.12
1241  2009     12    7   25.8  293.42  26.45   53.8   65.7
1242  2009     12    8  25.93  293.82  26.25  53.28  64.97
1243  2009     12    9  27.01   294.8  26.38   53.6  64.82
1244  2009     12   10  26.82  296.05  26.52   53.6  64.48
1245  2009     12   11  26.58  295.55   26.5  53.68  64.86
1246  2009     12   14   26.9  298.16  26.73  54.26  62.06
1247  2009     12   15  26.51  296.87  26.65  53.49   61.6
1248  2009     12   16  26.63  299.18  26.72  53.53  60.94
1249  2009     12   17   26.2  297.27  26.28  53.04  60.75
1250  2009     12   18  26.69  298.51  26.95   53.0  60.74
1251  2009     12   21  27.07  299.64   27.1  52.79  61.01
1252  2009     12   22  27.36  300.86  27.36  52.79  61.07
1253  2009     12   23   27.6  306.15  27.45   52.8  60.79
1254  2009     12   24  28.54  309.55  27.52  52.77  61.15
1255  2009     12   28  28.89  311.75  27.67  52.75  61.52
1256  2009     12   29  28.55  310.01  27.87  53.03  61.31
1257  2009     12   30   28.9  311.68  27.49  52.85  61.24
1258  2009     12   31  28.77   310.3  27.06  52.21  60.73

[1259 rows x 8 columns]

Question 2. 
-----------
The file ("TechTickerSampleData.txt") starts with a header of 7 lines. Afterward, the data part is tab delimited and contains tick data for AAPL and MSFT. The first column specifies if the tick information is for AAPL or MSFT. The second column is the timestamp of the tick data in minutes, and the meaning of the following 5 columns can be read off of line number 5: Close, High, Low, Open, Volume. 

Create a `DataFrame`, making the second column the index.

In [6]:
pd.read_table("TechTickerSampleData.txt",header=7,index_col=2)

         AAPL    0  84.6257  84.5714  84.5714.1   568330
84.5993
40.2800  MSFT    0  40.2800  40.2100    40.2401   542320
40.1900  MSFT    1  40.3600  40.1700    40.2900  2596758
40.1750  MSFT    2  40.2300  40.0700    40.1900  2433238
84.8871  AAPL    2  84.9714  84.4300    84.5871  5143782
40.0900  MSFT    3  40.1800  40.0800    40.1800  1912087
84.8457  AAPL    3  84.9543  84.7571    84.8786  3119410
40.1300  MSFT    4  40.1500  40.0700    40.0900  1425872
84.4715  AAPL    4  84.9414  84.4300    84.8571  2805446
84.1600  AAPL    5  84.6329  84.0400    84.4817  5049219
40.1630  MSFT    6  40.2000  40.1200    40.1400  1057386
83.8929  AAPL    6  84.2527  83.7657    84.1601  3386593
84.1800  AAPL    7  84.2043  83.8214    83.9143  2441691
40.0400  MSFT    8  40.1500  40.0250    40.1352   830479
84.0943  AAPL    8  84.2071  83.9814    84.1739  1349978
39.9700  MSFT    9  40.0500  39.9500    40.0400  2709454
39.9950  MSFT   10  40.0000  39.9600    39.9700  1688028
84.5166  AAPL   10  84.5814  84.3714    84.4214  1822870
39.9800  MSFT   11  40.0000  39.9600    39.9940  1404386
84.5143  AAPL   11  84.6314  84.4486    84.5014  2166633
40.0000  MSFT   12  40.0450  39.9650    39.9750  2170004
84.2429  AAPL   12  84.5429  84.2271    84.5171  2253258
40.0000  MSFT   13  40.0100  39.9500    39.9900  6820612
84.4971  AAPL   13  84.4986  84.1643    84.2243  4716439
40.2900  MSFT   48  40.3200  40.2800    40.3100  1140301
39.8750  MSFT   49  40.3400  39.8400    40.2900  4144519
39.9800  MSFT   50  40.0200  39.8450    39.8750  3178738
39.8600  MSFT   51  40.0400  39.8400    39.9800  2289461
84.4614  AAPL   51  84.6829  84.2443    84.6143  4026218
39.7900  MSFT   52  39.9600  39.7700    39.8500  1377684
84.4500  AAPL   52  84.5857  84.4114    84.4714  1667743
...       ...  ...      ...      ...        ...      ...
41.7900  MSFT  348  41.8150  41.7100    41.7900  1445177
95.1100  AAPL  348  95.1700  94.9700    95.1050  1858039
41.6850  MSFT  349  41.8300  41.6700    41.8200  3404465
95.0350  AAPL  349  95.1700  94.9700    95.1500  2449449
41.6850  MSFT  350  41.6850  41.6850    41.6850      122
41.7800  MSFT  384  41.8000  41.7000    41.7000   475538
95.3300  AAPL  384  95.3800  95.3300    95.3600   473563
41.5000  MSFT  385  41.7800  41.4800    41.7700  3126191
95.3000  AAPL  385  95.6200  94.9600    95.3400  5032743
41.6050  MSFT  386  41.6100  41.4800    41.5100  1715520
95.5390  AAPL  386  95.8900  95.1800    95.3090  4398637
41.7300  MSFT  387  41.7300  41.5500    41.6100  1083479
95.6700  AAPL  387  95.7900  95.4900    95.5350  1789334
41.8000  MSFT  388  41.8500  41.7100    41.7300  1250176
95.4000  AAPL  388  95.7500  95.3300    95.6650  1791034
41.8000  MSFT  389  41.8900  41.8000    41.8100  1049825
95.3400  AAPL  389  95.5000  95.2200    95.4000  1791164
41.8400  MSFT  390  41.8600  41.7800    41.8000   960177
95.1300  AAPL  390  95.3400  95.0800    95.3399  1226239
41.8810  MSFT  391  41.9100  41.8400    41.8400   842344
95.0277  AAPL  391  95.2300  94.9300    95.1200  1412825
41.8900  MSFT  392  41.9500  41.8800    41.8858   950716
95.1650  AAPL  392  95.2500  95.0100    95.0250  1195498
41.9300  MSFT  393  41.9500  41.8800    41.8965  1008343
95.0050  AAPL  393  95.1900  94.9900    95.1763  1116781
41.9650  MSFT  394  41.9750  41.9100    41.9390  1119940
95.0300  AAPL  394  95.0900  94.8625    95.0076  1726397
41.9600  MSFT  395  42.0150  41.9500    41.9680  1359014
95.0500  AAPL  395  95.1600  95.0000    95.0358  1338130
41.9850  MSFT  396  41.9900  41.9500    41.9670   386750

[1406 rows x 6 columns]

Bonus
=====

Question 3. 
-----------
The file ("HistoricalS_and_P500.csv") is comma separated and contains historical data for the S&P200 index since **1950**. The first column contains the date in the format MM/DD/YY. We would like to make these dates the index of the `DataFrame` created. The next 6 columns are the usual values for a given day. The name of the columns is stated at the top of the file.

1. Try to do a simple `read_table` on the file, parsing the dates in the data (see `parse_dates`), and using the first column as an index. Look at the date range of the resulting dataframe.
2. To fix this issue, we will need to help the date parser. Have a look to the `read_table` documentation (see `converters`). You will see that that can be done by providing our own date parser, or modifying the string as it comes in to add the century number the way we want. Write a function that converts a date formatted as MM/DD/YY and make it YYYY-MM-DD.
3. Use that function to improve your `read_table` call.

In [7]:
import datetime
import re
originalYear=50
def dateparser(date):
    month=int(re.search(r'([0-3]?[0-9])[/]',date).group(1))
    day=int(re.search(r'[/]([0-3]?[0-9])[/]',date).group(1))
    year=int(re.search(r'[/]([0-9][0-9])',date).group(1))
    if(year>=originalYear):
        year+=1900
    else:
        year+=2000
    return '{}-{}-{}'.format(year,month,day)
pd.read_csv("HistoricalS_and_P500.csv",parse_dates=True,converters={'Date':dateparser})

            Date     Open     High      Low    Close      Volume  Adj Close
0       2014-7-8  1976.39  1976.39  1959.46  1963.71  3302430000    1963.71
1       2014-7-7  1984.22  1984.22  1974.88  1977.65  2681260000    1977.65
2       2014-7-3  1975.88  1985.59  1975.88  1985.44  1998090000    1985.44
3       2014-7-2  1973.06  1976.67  1972.58  1974.62  2851480000    1974.62
4       2014-7-1  1962.29  1978.58  1962.29  1973.32  3188240000    1973.32
5      2030-6-30  1960.79  1964.24  1958.22  1960.23  3037350000    1960.23
6      2027-6-27  1956.56  1961.47  1952.18  1960.96  4290590000    1960.96
7      2026-6-26  1959.89  1959.89  1944.69  1957.22  2778840000    1957.22
8      2025-6-25  1949.27  1960.83  1947.49  1959.53  3106710000    1959.53
9      2024-6-24  1961.97  1968.17  1948.34  1949.98  3089700000    1949.98
10     2023-6-23  1962.92  1963.74  1958.89  1962.61  2717630000    1962.61
11     2020-6-20  1960.45  1963.91  1959.17  1962.87  4336240000    1962.87
12     2019-6-19  1957.50  1959.87  1952.26  1959.48  2952150000    1959.48
13     2018-6-18  1942.73  1957.74  1939.29  1956.98  3065220000    1956.98
14     2017-6-17  1937.15  1943.69  1933.55  1941.99  2971260000    1941.99
15     2016-6-16  1934.84  1941.15  1930.91  1937.78  2926130000    1937.78
16     2013-6-13  1930.80  1937.30  1927.69  1936.16  2598230000    1936.16
17     2012-6-12  1943.35  1943.35  1925.78  1930.11  3040480000    1930.11
18     2011-6-11  1949.37  1949.37  1940.08  1943.89  2710620000    1943.89
19     2010-6-10  1950.34  1950.86  1944.64  1950.79  2702360000    1950.79
20      2014-6-9  1948.97  1955.55  1947.16  1951.27  2812180000    1951.27
21      2014-6-6  1942.41  1949.44  1942.41  1949.44  2864300000    1949.44
22      2014-6-5  1928.52  1941.74  1922.93  1940.46  3113270000    1940.46
23      2014-6-4  1923.06  1928.63  1918.60  1927.88  2793920000    1927.88
24      2014-6-3  1923.07  1925.07  1918.79  1924.24  2867180000    1924.24
25      2014-6-2  1923.87  1925.88  1915.98  1924.97  2509020000    1924.97
26     2030-5-30  1920.33  1924.03  1916.64  1923.57  3263490000    1923.57
27     2029-5-29  1910.60  1920.03  1909.82  1920.03  2709050000    1920.03
28     2028-5-28  1911.77  1914.46  1907.30  1909.78  2976450000    1909.78
29     2027-5-27  1902.01  1912.28  1902.01  1911.91  2911020000    1911.91
...          ...      ...      ...      ...      ...         ...        ...
16202  2014-2-14    17.06    17.06    17.06    17.06     2210000      17.06
16203  2010-2-10    17.24    17.24    17.24    17.24     1790000      17.24
16204   1950-2-9    17.28    17.28    17.28    17.28     1810000      17.28
16205   1950-2-8    17.21    17.21    17.21    17.21     1470000      17.21
16206   1950-2-7    17.23    17.23    17.23    17.23     1360000      17.23
16207   1950-2-6    17.32    17.32    17.32    17.32     1490000      17.32
16208   1950-2-3    17.29    17.29    17.29    17.29     2210000      17.29
16209   1950-2-2    17.23    17.23    17.23    17.23     2040000      17.23
16210   1950-2-1    17.05    17.05    17.05    17.05     1810000      17.05
16211  2031-1-31    17.05    17.05    17.05    17.05     1690000      17.05
16212  2030-1-30    17.02    17.02    17.02    17.02     1640000      17.02
16213  2027-1-27    16.82    16.82    16.82    16.82     1250000      16.82
16214  2026-1-26    16.73    16.73    16.73    16.73     1150000      16.73
16215  2025-1-25    16.74    16.74    16.74    16.74     1700000      16.74
16216  2024-1-24    16.86    16.86    16.86    16.86     1250000      16.86
16217  2023-1-23    16.92    16.92    16.92    16.92     1340000      16.92
16218  2020-1-20    16.90    16.90    16.90    16.90     1440000      16.90
16219  2019-1-19    16.87    16.87    16.87    16.87     1170000      16.87
16220  2018-1-18    16.85    16.85    16.85    16.85     1570000      16.85
16221  2017-1-17    16.86    16.86    16.86    16.86     1790000      16.86
16222  2016-1-16    16.72    16.72    16.72    16.72     1460000      16.72
16223  2013-1-13    16.67    16.67    16.67    16.67     3330000      16.67
16224  2012-1-12    16.76    16.76    16.76    16.76     2970000      16.76
16225  2011-1-11    17.09    17.09    17.09    17.09     2630000      17.09
16226  2010-1-10    17.03    17.03    17.03    17.03     2160000      17.03
16227   1950-1-9    17.08    17.08    17.08    17.08     2520000      17.08
16228   1950-1-6    16.98    16.98    16.98    16.98     2010000      16.98
16229   1950-1-5    16.93    16.93    16.93    16.93     2550000      16.93
16230   1950-1-4    16.85    16.85    16.85    16.85     1890000      16.85
16231   1950-1-3    16.66    16.66    16.66    16.66     1260000      16.66

[16232 rows x 7 columns]

Question 4. 
-----------
The file ("HistoricalNASDAQ.htm") is an html file with daily NASDAQ index returns. The description of the columns is again provided on the first line of the table. Return a `DataFrame` whose index is the date column.

Advice: Parsing html is always a complicated task. Reading the help on `read_html` is highly recommended. In particular, the default value for `header` may cause issues.

In [ ]:
pd.read_html?

In [ ]:
import pandas as pd
pd.read_html("HistoricalNASDAQ.htm",parse_dates=True,header=0,index_col=0)